/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdraft;

import java.util.*;
import java.awt.Component;
import java.awt.event.ItemListener;
import java.sql.Connection;
import javax.swing.*;
import javax.swing.JPanel;

/**
 *
 * @author saman
 */
public class AppDraftGUI extends javax.swing.JFrame {

    /**
     * Creates new form AppDraftGUI
     */
    
    public String mentorUsername;
    private SQLDatabase database;
    public HomeScreen p0; 
    public MentorForm p1; 
    public MentorsList p2;
    public DisplayEvents p3; 
    //private static Connection connect;
    
    private ArrayList<JPanel> panels;

    public SQLDatabase getDatabase() {
        return database;
    }
    
    
    public AppDraftGUI() {
        
        panels = new ArrayList<JPanel>();
        
        initComponents();
        this.getContentPane().getWidth();
        this.getContentPane().getHeight();
        p0 = new HomeScreen(this);
        p1 = new MentorForm(this);
        p2 = new MentorsList(this);
        p3 = new DisplayEvents(this);
        this.add(p0);
        this.add(p1);
        this.add(p2);
        this.add(p3);
        panels.add(p0);
        panels.add(p1);
        panels.add(p2);
        panels.add(p3);
        
        
        
        this.pack();
     
        for (int i = 0; i < panels.size(); i++) {
            panels.get(i).setLocation(0,0);
            panels.get(i).setSize(this.getWidth(), this.getHeight());
            panels.get(i).setVisible(false);
        }
        panels.get(0).setVisible(true);
        
        database = SQLDatabase.getInstance();
    }
    
    public void showPanel(int panelNum){
        for (int i = 0; i < panels.size(); i++) {
            panels.get(i).setVisible(false);
        }
        panels.get(panelNum).setVisible(true);
    }
    
    public JPanel getPanel(int n){
        return panels.get(n);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppDraftGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppDraftGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppDraftGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppDraftGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AppDraftGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
