/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdraft;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author saman
 */
public class HomeScreen extends javax.swing.JPanel {

    private SQLDatabase database;
    private AppDraftGUI frameInstance;

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen(AppDraftGUI frameInstance) {
        initComponents();
        database = SQLDatabase.getInstance();
        this.frameInstance = frameInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        afkTitle = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();

        setBackground(new java.awt.Color(170, 212, 212));

        afkTitle.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 48)); // NOI18N
        afkTitle.setText("ATHLETES FOR KIDS");

        usernameLbl.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        usernameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLbl.setText("Username: ");

        passwordLbl.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        passwordLbl.setText("Password: ");

        submitBtn.setBackground(new java.awt.Color(255, 255, 255));
        submitBtn.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(118, 219, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passwordLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usernameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(369, 369, 369))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(afkTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(afkTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLbl)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLbl))
                .addGap(90, 90, 90)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        //ignore can't delete
    }//GEN-LAST:event_submitBtnActionPerformed

    //when user clicks submit, check if they are a mentor, admin, or invalid user and let them into the according JPanel
    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
        currentMentor user = new currentMentor(username.getText(), password.getText());
        if (database.checkUser(user.getUsername(), user.getPassword()) == 1){
            frameInstance.p2.populateMList();
            ((AppDraftGUI) this.getRootPane().getParent()).showPanel(2);
            //if user is admin Marni, let her into the admin page to manage mentors
        } else  if (database.checkUser(user.getUsername(), user.getPassword()) == 2) {
            ((AppDraftGUI) this.getRootPane().getParent()).showPanel(1);
            //if user is a mentor, let them into the mentor input page
        } else {
            Component frame = null;
            //show error message, wrong username and password
            JOptionPane.showMessageDialog(frame, "Invalid username or password.");
        }
        int currentID = database.getID(user.getUsername());
        frameInstance.p1.setCurrentID(currentID);
        //save current mentor ID for later reference
    }//GEN-LAST:event_submitBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afkTitle;
    public javax.swing.JTextField password;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JButton submitBtn;
    public javax.swing.JTextField username;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}

/*

*/
