/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdraft;

import javax.swing.*;
import static appdraft.SQLDatabase.*;
import java.awt.Component;
import java.util.Scanner;

/**
 *
 * @author saman
 */
public class MentorForm extends javax.swing.JPanel {

    /**
     * Creates new form MentorForm
     */
    private int currentID;
    private AppDraftGUI frameInstance;
    private SQLDatabase database;

    public MentorForm(AppDraftGUI frameInstance) {
        initComponents();
        this.frameInstance = frameInstance;
        database = SQLDatabase.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLbl = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        pleaseLbl = new javax.swing.JLabel();
        hoursLb = new javax.swing.JLabel();
        hours = new javax.swing.JTextField();
        describeLb = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(170, 212, 212));

        dateLbl.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        dateLbl.setText("Date: ");

        pleaseLbl.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 18)); // NOI18N
        pleaseLbl.setText("Please Describe Your Meeting with Your Buddy:");

        hoursLb.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        hoursLb.setText("Hours: ");

        describeLb.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        describeLb.setText("Description of Activity: ");

        submitBtn.setBackground(new java.awt.Color(255, 255, 255));
        submitBtn.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pleaseLbl)
                        .addContainerGap(385, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(hoursLb)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(describeLb)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(submitBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLbl)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69)
                .addComponent(pleaseLbl)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursLb)
                    .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(describeLb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitBtn)
                .addGap(90, 90, 90))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setCurrentID(int ID) {
        currentID = ID;
    }

    //when mentor clicks submit, save their inputted data as a new column in EVENTS SQL table
    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
        Scanner check = new Scanner(hours.getText());
        if (check.hasNextDouble() || check.hasNextInt()) {
            Meeting m = new Meeting(date.getText(), hours.getText(), description.getText(), currentID);
            database.setInfo(m.getDate(), m.getHours(), m.getDescription(), m.getMentorID());
            //input meeting info to EVENTS table under the correct column
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Event successfully submitted!");
        } else {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Error: Please enter a valid number of hours");
            //if bad user input, show error message
        }
    }//GEN-LAST:event_submitBtnMouseClicked

    //when logout, show login screen and clear all saved variables
    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        ((AppDraftGUI) this.getRootPane().getParent()).showPanel(0);
        frameInstance.p0.username.setText("");
        frameInstance.p0.password.setText("");
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        //ignore cant delete
    }//GEN-LAST:event_logoutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel describeLb;
    private javax.swing.JTextArea description;
    private javax.swing.JTextField hours;
    private javax.swing.JLabel hoursLb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel pleaseLbl;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
