/*

create JTable:
create array with column names
create 2d array with all the info to go into the table:
    basically get query to select all info from ALLMENTORS, then push that data into the Jtable to display it
Then when you double click on a mentor, show a JPanel with a table of their events (with back button to go back)

 */
package appdraft;

import java.sql.*;

import java.util.*;
import javax.swing.*;


/**
 *
 * @author saman
 */
public class MentorsList extends javax.swing.JPanel {
    
    private ArrayList<String> list;
    public SQLDatabase database;
    private String[] info;
    private AppDraftGUI frameInstance;
    public String tempMentor;
    public int id;
    
    
    /**
     * Creates new form MentorsList
     */
    public MentorsList(AppDraftGUI frameInstance) {
        initComponents();
        database = SQLDatabase.getInstance();
        this.frameInstance = frameInstance;
    }
    
    //sets the array list as all mentors
    public void setArray(){
        list = database.getMentorsList();
    }
    
    //converts array list to array
    public void convertArray(){
        info = new String[list.size()];
        for (int i = 0; i < list.size(); i++) {
            info[i] = list.get(i);
        }
    }
    
    //displays array in JList
    public void populateMList(){
        setArray();
        convertArray();
        DefaultListModel dlm = new DefaultListModel();
        for (int i = 0; i < info.length; i++) {
            dlm.addElement(info[i]);
        }
        mentorList.setModel(dlm);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mentorsLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mentorList = new javax.swing.JList<>();
        logoutBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(170, 212, 212));

        mentorsLbl.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        mentorsLbl.setText("Mentors: ");

        mentorList.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        mentorList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        mentorList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mentorListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mentorList);

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(103, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mentorsLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutBtn)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mentorsLbl)
                    .addComponent(logoutBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    //sets int id as the id of the mentor selected
    public void setSelectedID(String x){
        Scanner sc = new Scanner(x);
                if (sc.hasNextInt()) {
                    this.id = sc.nextInt() - 1;
                }
    }
    

    //when a mentor is double clicked on, show the events of that mentor
    private void mentorListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mentorListMouseClicked
        JList theList = (JList) evt.getSource();
        if (evt.getClickCount() == 2){
            int index = theList.locationToIndex(evt.getPoint());
            if (index >= 0){
                Object o = theList.getModel().getElementAt(index);
                tempMentor = o.toString();
                //System.out.println("Double-clicked on: " + tempMentor);
                //System.out.println(o.toString());
                setSelectedID(tempMentor);
                //frameInstance.p3.test();
                frameInstance.p3.populateEList(this.id);
                ((AppDraftGUI) this.getRootPane().getParent()).showPanel(3);
            }
        }
    }//GEN-LAST:event_mentorListMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        ((AppDraftGUI) this.getRootPane().getParent()).showPanel(0);
        frameInstance.p0.username.setText("");
        frameInstance.p0.password.setText("");
    }//GEN-LAST:event_logoutBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JList<String> mentorList;
    private javax.swing.JLabel mentorsLbl;
    // End of variables declaration//GEN-END:variables
}
